version: "3.9"
services:
  nodejs:
    container_name: carcare_web_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    # image: node:16-bullseye-slim
    volumes:
    - "./backend:/src"
    - /src/node_modules/bcrypt/
    ports:
      - "4600:4600"
    networks:
      - carcare-network 
      
    restart: always
  # carcare_web:
  carcare_web:
    container_name: carcare_web_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

    ports:
      - 3388:3388
      - 443:443
    env_file: ./frontend/.env
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"


  certbot:
    image: certbot/certbot
    networks:
      - nginx-tier
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    depends_on:
      - carcare_web_frontend
    command: "certonly --webroot --webroot-path=/usr/share/nginx/html --email folkafterme67@gmail.com --agree-tos --no-eff-email --staging -d careubon.com  -d careubon.com" 

volumes:
  certbot-etc:
  certbot-var:
#   db:
#     image: postgres
#     container_name: local_pgdb
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: folk!@#1234
#     volumes:
#       - local_pgdata:/var/lib/postgresql/data
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin4_container
#     restart: always
#     ports:
#       - "8888:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: folkafterme67@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin

# volumes:
#   local_pgdata:
#   pgadmin-data:
    
networks:
  carcare-network:
    driver: bridge