version: "3.9"
services:
  nodejs:
    container_name: carcare_web_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    # image: node:16-bullseye-slim
    volumes:
    - "./backend:/src"
    - /src/node_modules/bcrypt/
    ports:
      - "4600:4600"
    networks:
      - carcare-network 
      
    restart: unless-stopped
  # carcare_web:
  carcare_web:
    container_name: carcare_web_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

      - ./learneducation.co.th.cer:/etc/nginx/ssl/live/lol360.learneducation.co.th/learneducation.co.th.cer
      - ./learneducation.co.th.key:/etc/nginx/ssl/live/lol360.learneducation.co.th/learneducation.co.th.key

    ports:
      - 3388:3388
      - 443:443
    env_file: ./frontend/.env
    
networks:
  carcare-network:
    driver: bridge